import crypto from 'crypto';

import type { Booking, EventType, User } from '@prisma/client';
import type { CreateBookingInput, UpdateBookingStatusInput } from '@scaler/types';
import { ERROR_CODE, HTTP_STATUS, BOOKING_STATUS } from '../config/constants';
import { eventBus, EVENTS } from '../lib/event-bus';
import { prisma } from '../lib/prisma';
import { AppError } from '../utils/app-error';
import { OverlapUtils } from '../utils/overlap';

export type BookingWithRelations = Booking & {
  event_type: EventType;
};

export type FullBookingWithRelations = Booking & {
  event_type: EventType;
  host: User;
};

export class BookingService {
  static async getBookings(userId: string): Promise<BookingWithRelations[]> {
    return prisma.booking.findMany({
      where: { host_id: userId },
      include: {
        event_type: true,
      },
      orderBy: { start_time: 'desc' },
    });
  }

  static async getBookingById(userId: string, id: string): Promise<BookingWithRelations> {
    const booking = await prisma.booking.findUnique({
      where: { id },
      include: { event_type: true },
    });

    if (!booking || booking.host_id !== userId) {
      throw new AppError('Booking not found', HTTP_STATUS.NOT_FOUND, ERROR_CODE.NOT_FOUND);
    }

    return booking;
  }

  /**
   * Core transactional booking logic ensuring double-booking prevention via row-level locks
   */
  static async createBooking(data: CreateBookingInput): Promise<FullBookingWithRelations> {
    const eventType = await prisma.eventType.findUnique({
      where: { id: data.event_type_id },
      include: { user: true },
    });

    if (!eventType || !eventType.is_active || eventType.deleted_at) {
      throw new AppError('Event type not available', HTTP_STATUS.NOT_FOUND, ERROR_CODE.NOT_FOUND);
    }

    const startTime = new Date(data.start_time);
    const endTime = new Date(data.end_time);

    // 1. Transaction to prevent double booking
    const booking = await prisma.$transaction(async (tx) => {
      // Row-level lock using raw SQL to prevent race conditions during slot claiming
      const overlapping: { id: string }[] = await tx.$queryRaw(
        OverlapUtils.getOverlapQuery(eventType.user_id, startTime, endTime),
      );

      if (overlapping.length > 0) {
        throw new AppError(
          'This time slot has already been booked',
          HTTP_STATUS.CONFLICT,
          ERROR_CODE.CONFLICT,
        );
      }

      // Status depends on event type settings
      const status = eventType.requires_confirmation
        ? BOOKING_STATUS.PENDING
        : BOOKING_STATUS.CONFIRMED;

      // Mock meeting URL generation (ideally this would be generated by Zoom/Google Meet Integration Service)
      let meetingUrl = null;
      if (eventType.location_type === 'GOOGLE_MEET') {
        meetingUrl = 'https://meet.google.com/mock-url';
      }
      if (eventType.location_type === 'ZOOM') {
        const meetingId = crypto.randomBytes(4).readUInt32BE(0).toString().padStart(10, '0');
        meetingUrl = `https://zoom.us/j/${meetingId}`;
      }

      // Create booking record
      return tx.booking.create({
        data: {
          event_type_id: eventType.id,
          host_id: eventType.user_id,
          guest_name: data.guest_name,
          guest_email: data.guest_email,
          guest_notes: data.guest_notes,
          start_time: startTime,
          end_time: endTime,
          status,
          meeting_url: meetingUrl,
        },
        include: {
          event_type: true,
          host: true,
        },
      });
    });

    // 2. Dispatch Post-Booking Actions asynchronously via Event Bus
    if (booking.status === BOOKING_STATUS.CONFIRMED) {
      eventBus.emit(EVENTS.BOOKING_CREATED, { booking, timezone: data.timezone });
    }

    return booking;
  }

  static async updateBookingStatus(
    userId: string,
    id: string,
    data: UpdateBookingStatusInput,
    hostTimezone: string,
  ): Promise<Booking> {
    const booking = await this.getBookingById(userId, id);

    // Fetch full relations for notifications
    const fullBooking = await prisma.booking.findUniqueOrThrow({
      where: { id },
      include: { event_type: true, host: true },
    });

    const updated = await prisma.booking.update({
      where: { id },
      data: {
        status: data.status,
        cancellation_reason: data.cancellation_reason,
      },
    });

    // Handle notifications
    if (data.status === BOOKING_STATUS.CANCELLED && booking.status !== BOOKING_STATUS.CANCELLED) {
      // Pass fullBooking and indicate it was cancelled by the host
      eventBus.emit(EVENTS.BOOKING_CANCELLED, {
        booking: {
          ...fullBooking,
          status: data.status,
          cancellation_reason: data.cancellation_reason ?? null,
        },
        timezone: hostTimezone,
        isHost: true,
      });
    } else if (
      data.status === BOOKING_STATUS.CONFIRMED &&
      booking.status === BOOKING_STATUS.PENDING
    ) {
      eventBus.emit(EVENTS.BOOKING_CREATED, {
        booking: { ...fullBooking, status: data.status },
        timezone: hostTimezone,
      });
    }

    return updated;
  }
}
